#!/bin/bash

# Generated by ChatGPT
# Set the minimum number of parameters and the server URL
MINPARAMS=1
PDSERVER="https://pixeldrain.com"

# Check if at least one file is provided
if [ $# -lt $MINPARAMS ]; then
    echo "Usage: $0 file1 [file2 ...]"
    exit 1
fi

# Loop through all provided file paths
for FILE in "$@"; do
    # Extract the base filename
    FILENAME="${FILE##*/}"
    
    echo "Uploading $FILENAME ... "
    
    # Upload the file and capture the response
    RESPONSE=$(curl -s -F "name=$FILENAME" -F "file=@$FILE" "$PDSERVER/api/file")
    
    # Extract the file ID from the response using jq (safer and more reliable than regex)
    FILEID=$(echo "$RESPONSE" | jq -r '.id')
    
    # Provide the direct URL to the uploaded file
    if [ -n "$FILEID" ]; then
        echo "Your file URL: $PDSERVER/u/$FILEID"
    else
        echo "Failed to upload $FILENAME"
    fi
done

echo "" # script completed 
